config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails do
    resources :doses, only: [ :new, :create ]
  end

  resources :doses, only: :destroy
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
  mount_uploader :photo, PhotoUploader
  validates :photo, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient
  validates :description, presence: true
  validates_uniqueness_of :cocktail, :scope => [:ingredient]
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  rescue  Cloudinary::CarrierWave::UploadError
    @cocktail.errors.add(:photo, 'file too large')
    render :new
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :ingredient, :dose, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def index
    @doses = Dose.all
  end

  def show
    @dose = Dose.find(params[:id])
  end

  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @dose = Dose.new(dose_params)
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    # @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id, :cocktail_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/index.html.erb
<%= render "shared/banner" %>
<div class="container">
  <h1> My cocktails</h1>
  <div class="row">
    <% @cocktails.each do |cocktail| %>
      <div class="col-xs-12 col-sm-4">
        <%= render "shared/cards", cocktail: cocktail %>
      </div>
    <% end %>
  </div>
</div>

app/views/cocktails/new.html.erb
<h2> New cocktail</h2>
<%= simple_form_for [@cocktail] do |f| %>
  <%= f.input :name %>
  <%= f.input :photo %>
  <%= f.input :photo_cache, as: :hidden %>
  <%= f.submit %>
<% end %>

app/views/cocktails/show.html.erb
<% if @cocktail.photo.stored_version  %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),url('<%= cl_image_path(@cocktail.photo) %>');">
<% else %>
  <div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),url('<%= cl_image_path('mojito-500_cypmat') %>');">
<% end %>
</div>
<div class="container">
  <h3>Ingredients</h3>
  <% doses = @cocktail.doses  %>
  <ul>
    <% doses.each do |dose|  %>
    <li>
      <%= dose.description  %>
      <%= dose.ingredient.name  %>
      <%= link_to '<i class="fa fa-trash-o" aria-hidden="true"></i>'.html_safe, dose_path(@cocktail, dose),
      method: :delete, data: {confirm: "Are your sure?"} %> <br>
    <% end  %>
  <%= link_to "Add dose", new_cocktail_dose_path(@cocktail) %>
  </ul>
</div>
  <div class="btn-medium"><%= link_to "Back to list", cocktails_path %></div>

app/views/doses/index.html.erb
<h2>My doses</h2>
<ul>
<% @doses.each do |dose| %>
<li> <%= dose.description %> </li>
<% end %>
</ul>

app/views/doses/new.html.erb
<h2> New dose</h2>
<%= simple_form_for([@cocktail, @dose]) do |f| %>
<%= f.input :description %>
<%= f.association :ingredient %>
<%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyGoodCocktails</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>
  <body>
    <%= render "shared/navbar" %>
    <%= yield %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag "application" %>
    <%= render "shared/footer" %>
  </body>
</html>

app/views/shared/_banner.html.erb
<div class="banner" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%),url('<%= image_path "cocktail_bar.jpg", class: "logo" %>');">
  <div class="banner-content">
    <h2>THE Mixologue</h2>
    <p>Discover our amazing cocktails</p>
  </div>
</div>

app/views/shared/_cards.html.erb
<% if cocktail.photo.present? %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.4) 50%), url('<%= cl_image_path(cocktail.photo) %>')">
<% else %>
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3) 0%, rgba(0,0,0,0.4) 50%), url('<%= cl_image_path('mojito-500_cypmat') %>')">
<% end %>
  <div class="card-category">
    <%= link_to cocktail.name, cocktail_path(cocktail) %>
  </div>
  <div class="card-description">
    <% cocktail.doses.each do |dose| %>
    <%= dose.description %> of <%= dose.ingredient.name %> <br>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fa fa-github"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    This footer is made with <i class="fa fa-heart"></i> at Le Wagon
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar-wagon">
  <!-- Logo -->
  <a href="/cocktails" class="navbar-wagon-brand">
    <%= image_tag "cocktail_logo.png", class: "logo" %>
  </a>

  <!-- Right Navigation -->
  <div class="navbar-wagon-right hidden-xs hidden-sm">

    <a href="/cocktails" class="navbar-wagon-item navbar-wagon-link">My cocktails</a>
    <a href="cocktails/new" class="navbar-wagon-item navbar-wagon-link">Add a new cocktail</a>

    <!-- Profile picture with dropdown list -->
    <div class="navbar-wagon-item">
      <div class="dropdown">
        <img src="https://kitt.lewagon.com/placeholder/users/alexialet" class="avatar dropdown-toggle" id="navbar-wagon-menu" data-toggle="dropdown">
        <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
          <li><a href="/cocktails">My cocktails</a></li>
          <li><a href="cocktails/new">Add cocktail</a></li>
        </ul>
      </div>
    </div>
  </div>

  <!-- Dropdown appearing on mobile only -->
  <div class="navbar-wagon-item hidden-md hidden-lg">
    <div class="dropdown">
      <i class="fa fa-bars dropdown-toggle" data-toggle="dropdown"></i>
      <ul class="dropdown-menu dropdown-menu-right navbar-wagon-dropdown-menu">
        <li><a href="/cocktails">My cocktails</a></li>
        <li><a href="cocktails/new">Add cocktail</a></li>
      </ul>
    </div>
  </div>
</div>